2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_setup.py:_flush():67] Configure stats pid to 1726229
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_setup.py:_flush():67] Loading settings from /home/speech/.config/wandb/settings
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_setup.py:_flush():67] Loading settings from /home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/wandb/settings
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/wandb/run-20250418_161955-9bpbt75d/logs/debug.log
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/wandb/run-20250418_161955-9bpbt75d/logs/debug-internal.log
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:init():781] calling init triggers
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:init():786] wandb.init called with sweep_config: {'activation': 'silu', 'batch_norm': True, 'batch_size': 64, 'dense_neurons': 512, 'dropout': 0.3, 'early_stopping_patience': 7, 'epochs': 15, 'filter_sizes': [3, 3, 5, 5, 7], 'lr': 0.0001, 'num_filters': [16, 32, 64, 64, 128], 'optimizer': 'sgd', 'scheduler_patience': 3, 'use_data_augmentation': False, 'use_scheduler': False, 'weight_decay': 0.0001}
config: {'data_dir': 'data/inaturalist_12K', 'epochs': 10, 'batch_size': 64, 'lr': 0.001, 'weight_decay': 0.0001, 'optimizer': 'adam', 'activation': 'relu', 'num_filters': [32, 64, 128, 128, 256], 'filter_sizes': [3, 5, 5, 7, 7], 'dense_neurons': 512, 'dropout': 0.1, 'batch_norm': False, 'use_wandb': True, 'wandb_project': 'cnn_from_scratch_project', 'use_data_augmentation': False, 'use_scheduler': False, 'scheduler_patience': 3, 'early_stopping_patience': 5, '_wandb': {}}
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:init():809] starting backend
2025-04-18 16:19:55,707 INFO    MainThread:1726229 [wandb_init.py:init():813] sending inform_init request
2025-04-18 16:19:55,709 INFO    MainThread:1726229 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 16:19:55,709 INFO    MainThread:1726229 [wandb_init.py:init():823] backend started and connected
2025-04-18 16:19:55,710 INFO    MainThread:1726229 [wandb_run.py:_config_callback():1327] config_cb None None {'activation': 'silu', 'batch_norm': True, 'batch_size': 64, 'dense_neurons': 512, 'dropout': 0.3, 'early_stopping_patience': 7, 'epochs': 15, 'filter_sizes': [3, 3, 5, 5, 7], 'lr': 0.0001, 'num_filters': [16, 32, 64, 64, 128], 'optimizer': 'sgd', 'scheduler_patience': 3, 'use_data_augmentation': False, 'use_scheduler': False, 'weight_decay': 0.0001}
2025-04-18 16:19:55,710 INFO    MainThread:1726229 [wandb_init.py:init():915] updated telemetry
2025-04-18 16:19:55,712 INFO    MainThread:1726229 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-18 16:19:56,395 INFO    MainThread:1726229 [wandb_init.py:init():1014] starting run threads in backend
2025-04-18 16:19:56,418 INFO    MainThread:1726229 [wandb_run.py:_console_start():2454] atexit reg
2025-04-18 16:19:56,418 INFO    MainThread:1726229 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-18 16:19:56,418 INFO    MainThread:1726229 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-18 16:19:56,418 INFO    MainThread:1726229 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-18 16:19:56,419 INFO    MainThread:1726229 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-18 16:20:00,150 INFO    MainThread:1726229 [wandb_watch.py:_watch():71] Watching
2025-04-18 16:20:45,739 INFO    MsgRouterThr:1726229 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-18 16:20:48,947 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,953 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,953 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,953 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,953 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,954 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,955 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,955 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,955 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,955 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,956 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 16:20:48,957 ERROR   MainThread:1726229 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
